### ISSUE TITLE
Use rstudioapi::modifyRange() for Addin

### ISSUE THREAD

**Issue by dracodoc** [krlmlr/styler#178] opened 2017-09-03 23:00 UTC
I have this `data.table` code:

```r
ranges[, non_white_char_total := {range_count = nchar(str_replace_all(text, "\\s*", ""))
                                         cumsum(range_count)}]
```
I selected it, used `style active region` addin menu and there is this error

```
Error in parse(text = text, keep.source = TRUE) : 
  <text>:3:0: unexpected end of input
1: ranges[, non_white_char_total := {
2:   range_count <- nchar(str_replace_all(text, "\\s*", ""))
  ^
```

**Comment by lorenzwalthert** [comment] 2017-09-04 08:01
Did you highlight all code? I think there are some problems with `rstudioapi`, the package that powers this feature of styler. I can reproduce the error when I first style the code (no error), then revert the changes via the menu Edit -> Back and then try to style again. After that, I get the error you get. 

Can you try to delete a letter (e.g. the first letter in your expression), manually inserting it again (instead of using Edit -> Back) so the code is again the same as the original code, save it, and try the Addin again?

Note that the file must be saved already for the Addins (styling of the active file or active region) to work, but I guess that was the case in your situation already.

**Comment by dracodoc** [comment] 2017-09-04 17:58
Originally my code was in a code chunk of RMarkdown, maybe that also caused some problem. I moved the code into a .R script, just like what you experienced, if Edit->back is used, the 2nd time will have this error.

I saw your code need to read the whole script as context, which also set the limit that file must be saved first. Is the whole context really needed? If you don't have to read context, you can also support RMarkdown directly.

**Comment by lorenzwalthert** [comment] 2017-09-05 08:51
I just tried styling a highlighted region in markdown and it seems to work fine on my side. The styling of whole markdown documents is on the todo list (#13).

I actually overlooked the function `rstudioapi::modifyRange()` which could do what you propose. It could simplify our code quite a bit, because essentially all internal functions for handling parts of lines etc. would be gone. Thanks for the hint 😊.

However, using such an approach seems to make it impossible to test the function because we have to provide the ID of the document we want to modify to `rstudioapi::modifyRange()` and that ID is usually returned by `getActiveDocumentContext()`. R CMD Check tests are ran in an isolated directory as far as I know, so we cannot "foresee" the ID of our document to style.

@krlmlr Do you think we should use `rstudioapi::modifyRange()` which simplifies our code and allows styling unsaved files and just bear with the fact that we can't test it anymore?

**Comment by lorenzwalthert** [comment] 2017-09-05 08:55
You can see here how much we can simplify, it's about 100 lines.
https://github.com/lorenzwalthert/styler/commit/1b74fb0e9942aa4a4ce26f24473c5dfd175a1bd2

**Comment by krlmlr** [comment] 2017-09-05 08:55
I haven't closely followed this thread, but `modifyRange()` seems fine with me. We still can mock it for testing.

**Comment by lorenzwalthert** [comment] 2017-09-05 09:20
I don't see how we can mock because we need the ID of the temporary  *-in.R file for `modifyRange()` (instead of a path), which is usually obtained via `getActiveDocumentContext()` but as we are not in an interactive session, we cannot call this function. Calling it via `source` in the *-in.R file gives context "console".

**Comment by dracodoc** [comment] 2017-09-05 12:55
I thought you need the whole file as context so I didn't suggest `modifyRange` directly at first. If you don't need it, then this definitely is much easier with a lot of advantages.

This part is interactive usage so it's naturally difficult to test automatically. I think as long as you have some test on the command line equivalent, this should be fine. The only part left untested is limited and easy to be tested by users.

You may want to test the selection first though, otherwise there might be some error if user clicked this menu without selecting anything. [I have some code like this](https://github.com/dracodoc/mischelper/blob/master/R/misc.R#L137):

```r
  context <- rstudioapi::getActiveDocumentContext()
  selection_start <- context$selection[[1]]$range$start
  selection_end <- context$selection[[1]]$range$end
  if (any(selection_start != selection_end)) { # text selected
```

**Comment by lorenzwalthert** [comment] 2017-09-18 16:47
The thing is I think you can't use `rstudioapi::modifyRange()` because we might return a longer or shorter expression (in terms of the number of lines). However, we could simply use `rstudioapi::insertText()` to first clear the range and then insert the text. I created #205 so @dracodoc if you want you can test it with 
```r
remotes::install_github("krlmlr/styler#205")
```
Can now also style unsaved files.

**Comment by dracodoc** [comment] 2017-09-18 17:01
Actually they should be same...

`?rstudioapi::modifyRange`

> modifyRange is a synonym for insertText, but makes its intent clearer when working with ranges, as performing text insertion with a range will replace the text previously existing in that range with new text.

#205 worked with the code example above without problem. I do find some other code result not optimal though:

```r
ranges[tag == "non_literal" & str_detect(text, ";"), 
       text := str_replace_all(text, ";", "\n")]
# become to this after styler
ranges[tag == "non_literal" & str_detect(text, ";"),
text := str_replace_all(text, ";", "\n")]
```

**Comment by lorenzwalthert** [comment] 2017-09-18 17:14
That's what I thought too and implemented it in bb7a2cd4 (my version with `modifyRange`) but I got:

```
Error: 'text' should either be length 1, or same length as 'ranges'
```
When styling 
```r
if (TRUE) {3} else {  1 + +1}
```
Which was supposed to become
```r
if (TRUE) {
  3
} else {  
  1 + +1
}
```


So I just worked around that using `insertText()`.

**Comment by dracodoc** [comment] 2017-09-18 17:18
Interesting, look at [this](https://github.com/rstudio/rstudioapi/blob/master/R/document-api.R#L86)

```r
modifyRange <- insertText
```

**Comment by dracodoc** [comment] 2017-09-18 17:22
I looked the code, the real difference is not from `modifyRange` or `insertText`. The API is only expecting one string, so you need to concatenate character vector into single string. Your newer version did this so it worked.

**Comment by lorenzwalthert** [comment] 2017-09-18 19:22
Thanks. You are absolutely right obviously. Don't know why I  did not get it 😜

**Comment by lorenzwalthert** [comment] 2017-09-18 19:25
Thanks. You are absolutely right obviously. Don't know why I can't solve this the right way. Looking forward to close this issue haha 😊

**Comment by lorenzwalthert** [comment] 2017-09-18 19:48
Regarding the other problem: I will file an issue.

**Comment by lorenzwalthert** [comment] 2017-09-18 19:59
Reference: #206

**Closed** 2017-09-19 21:45 UTC
Labels: Priority: Low, Status: WIP, Type: Infrastructure
